version: "3.9"

services:
  postgres:
    container_name: postgres_videoanalytics
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=my_username
      - POSTGRES_PASSWORD=my_password
    networks:
      - django_network
    volumes:
      - ./data:/var/lib/postgresql/data

  django:
    container_name: django_videoanalytics
    build:
      context: ./videoanalytics/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=my_database
      - POSTGRES_USER=my_username
      - POSTGRES_PASSWORD=my_password
    networks:
      - django_network
    # ${DEVICES}:
      # ${DEVICES_DASH} /dev/video0:/dev/video0
    volumes:
      - ./data:/var/lib/postgresql/data

networks:
  django_network:
    driver: bridge
